---
#Bring down stack
 - hosts: loadbalancer
   become: true
   tasks:
    - service: name=nginx state=stopped

 - hosts: webserver
   become: true
   tasks:
    - service: name=apache2 state=stopped

#Restart mysql
 - hosts: database
   become: true
   tasks:
    - service: name=mysql state=restarted
    
#Bring up stack
 - hosts: loadbalancer
   become: true
   user: iankesh
   tasks:
    - service: name=nginx state=started

 - hosts: webserver
   become: true
   tasks:
    - service: name=apache2 state=started
